package com.hotel.pojo;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer cusid;
	private Vip vip;
	private String cusname;
	private String cardid;
	private String cussex;
	private String custel;
	private Double balance;
	private Date cusbirth;
	private String address;
	private int status;
	private Set hotelaccounts = new HashSet(0);

	public Customer() {
	}

	public Customer(Vip vip, String cusname, String cardid, String cussex, String custel, Date cusbirth, String address,
			int status) {
		this.vip = vip;
		this.cusname = cusname;
		this.cardid = cardid;
		this.cussex = cussex;
		this.custel = custel;
		this.cusbirth = cusbirth;
		this.address = address;
		this.status = status;
	}

	public Customer(Vip vip, String cusname, String cardid, String cussex, String custel, Double balance, Date cusbirth,
			String address, int status, Set hotelaccounts) {
		this.vip = vip;
		this.cusname = cusname;
		this.cardid = cardid;
		this.cussex = cussex;
		this.custel = custel;
		this.balance = balance;
		this.cusbirth = cusbirth;
		this.address = address;
		this.status = status;
		this.hotelaccounts = hotelaccounts;
	}

	public Customer(Vip vip, String cusname, String cardid, String cussex, String custel, Double balance, Date cusbirth,
			String address,int parseInt) {
		super();
		this.vip = vip;
		this.cusname = cusname;
		this.cardid = cardid;
		this.cussex = cussex;
		this.custel = custel;
		this.balance = balance;
		this.cusbirth = cusbirth;
		this.address = address;
		this.status = parseInt;
	}
	/***********************ÐÂÔö***********************/
	

	public Customer(Integer cusid, Vip vip, String cusname, String cardid, String cussex, String custel, Double balance,
		Date cusbirth, String address, int status) {
	super();
	this.cusid = cusid;
	this.vip = vip;
	this.cusname = cusname;
	this.cardid = cardid;
	this.cussex = cussex;
	this.custel = custel;
	this.balance = balance;
	this.cusbirth = cusbirth;
	this.address = address;
	this.status = status;
}

	
	public Integer getCusid() {
		return this.cusid;
	}

	public void setCusid(Integer cusid) {
		this.cusid = cusid;
	}

	public Vip getVip() {
		return this.vip;
	}

	public void setVip(Vip vip) {
		this.vip = vip;
	}

	public String getCusname() {
		return this.cusname;
	}

	public void setCusname(String cusname) {
		this.cusname = cusname;
	}

	public String getCardid() {
		return this.cardid;
	}

	public void setCardid(String cardid) {
		this.cardid = cardid;
	}

	public String getCussex() {
		return this.cussex;
	}

	public void setCussex(String cussex) {
		this.cussex = cussex;
	}

	public String getCustel() {
		return this.custel;
	}

	public void setCustel(String custel) {
		this.custel = custel;
	}

	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

	public Date getCusbirth() {
		return this.cusbirth;
	}

	public void setCusbirth(Date cusbirth) {
		this.cusbirth = cusbirth;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Set getHotelaccounts() {
		return this.hotelaccounts;
	}

	public void setHotelaccounts(Set hotelaccounts) {
		this.hotelaccounts = hotelaccounts;
	}

}
