package com.hotel.pojo;


import java.util.HashSet;
import java.util.Set;

/**
 * Goods generated by hbm2java
 */
public class Goods implements java.io.Serializable {

	private Integer goodsid;
	private String goodsname;
	private int goodscount;
	private float goodsprice;
	private Set goodsconsumes = new HashSet(0);

	public Goods() {
	}

	public Goods(String goodsname, int goodscount, float goodsprice) {
		this.goodsname = goodsname;
		this.goodscount = goodscount;
		this.goodsprice = goodsprice;
	}

	public Goods(String goodsname, int goodscount, float goodsprice, Set goodsconsumes) {
		this.goodsname = goodsname;
		this.goodscount = goodscount;
		this.goodsprice = goodsprice;
		this.goodsconsumes = goodsconsumes;
	}

	public Integer getGoodsid() {
		return this.goodsid;
	}

	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	public String getGoodsname() {
		return this.goodsname;
	}

	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	public int getGoodscount() {
		return this.goodscount;
	}

	public void setGoodscount(int goodscount) {
		this.goodscount = goodscount;
	}

	public float getGoodsprice() {
		return this.goodsprice;
	}

	public void setGoodsprice(float goodsprice) {
		this.goodsprice = goodsprice;
	}

	public Set getGoodsconsumes() {
		return this.goodsconsumes;
	}

	public void setGoodsconsumes(Set goodsconsumes) {
		this.goodsconsumes = goodsconsumes;
	}

}
