package com.hotel.pojo;


import java.util.Date;

/**
 * Goodsconsume generated by hbm2java
 */
public class Goodsconsume implements java.io.Serializable {

	private Integer goodsconsumeid;
	private Guestroom guestroom;
	private Goods goods;
	private int goodsnum;
	private Date consumetime;

	public Goodsconsume() {
	}

	public Goodsconsume(Guestroom guestroom, Goods goods, int goodsnum, Date consumetime) {
		this.guestroom = guestroom;
		this.goods = goods;
		this.goodsnum = goodsnum;
		this.consumetime = consumetime;
	}

	public Integer getGoodsconsumeid() {
		return this.goodsconsumeid;
	}

	public void setGoodsconsumeid(Integer goodsconsumeid) {
		this.goodsconsumeid = goodsconsumeid;
	}

	public Guestroom getGuestroom() {
		return this.guestroom;
	}

	public void setGuestroom(Guestroom guestroom) {
		this.guestroom = guestroom;
	}

	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public int getGoodsnum() {
		return this.goodsnum;
	}

	public void setGoodsnum(int goodsnum) {
		this.goodsnum = goodsnum;
	}

	public Date getConsumetime() {
		return this.consumetime;
	}

	public void setConsumetime(Date consumetime) {
		this.consumetime = consumetime;
	}

}
