package com.hotel.pojo;

import java.util.HashSet;
import java.util.Set;

/**
 * Guestroom generated by hbm2java
 */
public class Guestroom implements java.io.Serializable {

	private Integer roomid;
	private int roomno;
	private String roomtype;
	private float roomprice;
	private int roomstatus;
	private String roomtel;
	private Float roomdiscount;
	private Set hotelaccounts = new HashSet(0);
	private Set goodsconsumes = new HashSet(0);

	public Guestroom() {
	}

	public Guestroom(int roomno, String roomtype, float roomprice, int roomstatus, String roomtel) {
		this.roomno = roomno;
		this.roomtype = roomtype;
		this.roomprice = roomprice;
		this.roomstatus = roomstatus;
		this.roomtel = roomtel;
	}

	public Guestroom(int roomno, String roomtype, float roomprice, int roomstatus, String roomtel, Float roomdiscount,
			Set hotelaccounts, Set goodsconsumes ) {
		this.roomno = roomno;
		this.roomtype = roomtype;
		this.roomprice = roomprice;
		this.roomstatus = roomstatus;
		this.roomtel = roomtel;
		this.roomdiscount = roomdiscount;
		this.hotelaccounts = hotelaccounts;
		this.goodsconsumes = goodsconsumes;
	}

	public Integer getRoomid() {
		return this.roomid;
	}

	public void setRoomid(Integer roomid) {
		this.roomid = roomid;
	}

	public int getRoomno() {
		return this.roomno;
	}

	public void setRoomno(int roomno) {
		this.roomno = roomno;
	}

	public String getRoomtype() {
		return this.roomtype;
	}

	public void setRoomtype(String roomtype) {
		this.roomtype = roomtype;
	}

	public float getRoomprice() {
		return this.roomprice;
	}

	public void setRoomprice(float roomprice) {
		this.roomprice = roomprice;
	}

	public int getRoomstatus() {
		return this.roomstatus;
	}

	public void setRoomstatus(int roomstatus) {
		this.roomstatus = roomstatus;
	}

	public String getRoomtel() {
		return this.roomtel;
	}

	public void setRoomtel(String roomtel) {
		this.roomtel = roomtel;
	}

	public Float getRoomdiscount() {
		return this.roomdiscount;
	}

	public void setRoomdiscount(Float roomdiscount) {
		this.roomdiscount = roomdiscount;
	}

	public Set getHotelaccounts() {
		return this.hotelaccounts;
	}

	public void setHotelaccounts(Set hotelaccounts) {
		this.hotelaccounts = hotelaccounts;
	}

	public Set getGoodsconsumes() {
		return this.goodsconsumes;
	}

	public void setGoodsconsumes(Set goodsconsumes) {
		this.goodsconsumes = goodsconsumes;
	}


}
